name: "EC2 Deployment"
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    steps:
    - name: checkout action
      uses: actions/checkout@v5
    
    - name: ssh action deploy opn the ec2 server
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd nodeapp/
          git pull origin main
          npm ci
          npm run build
          pm2 restart nodeapp